name: CI
on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]

permissions:
  contents: read
  packages: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Vet Code
        run: go vet ./...
      - name: Check Formatting
        run: gofmt -l .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Fetch Dependencies
        run: go get .
      - name: Run Tests
        run: go test ./...

  build:
    name: Build
    uses: ./.github/workflows/go-build.yml
    with:
      platforms: linux/amd64,linux/arm64,linux/arm,linux/386

  publish:
    name: Publish Docker Image
    needs: [test, build]
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/docker-publish.yml
    with:
      platforms: linux/amd64,linux/arm64,linux/arm,linux/386
