name: CI
on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/go-lint.yml

  test:
    name: Test
    uses: ./.github/workflows/go-test.yml

  build:
    name: Build
    uses: ./.github/workflows/go-build.yml
    with:
      platforms: linux/amd64,linux/arm64,linux/arm,linux/386

  publish:
    name: Publish
    if: ${{ github.event_name == 'push' }}
    needs: [test, build]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      platforms: linux/amd64,linux/arm64,linux/arm,linux/386
